version: '2'
services:
    web:
      image: myapi
      ports:
        - 8080:8080
      depends_on:
        - db
    db:
        container_name: url-postgres-db
        image: postgres:13.3
        volumes:
            - url-postgres-db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=db_user
            - POSTGRES_DB=url-management
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432

volumes:
    url-postgres-db: {}