app:
  dataSource:
    postgres:
      port: 5432
      username: db_user
      password: password
      host: localhost
      databaseName: url-management
      jdbc-url: jdbc:postgresql://${app.dataSource.postgres.host}:${app.dataSource.postgres.port}/${app.dataSource.postgres.databaseName}